kind: PersistentVolume
apiVersion: v1
metadata:
    name: app-pv
    namespace: shivang
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /mnt/data

