apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: app-mysql
  name: app-mysql
  namespace: shivang
spec:
  serviceName: mysqldb
  replicas: 1
  selector:
    matchLabels:
      app: app-mysql
  template:
    metadata:
      labels:
        app: app-mysql
    spec:
      containers:
      - name: mysql
        image: mysql:latest
        env:
          - name: MYSQL_DATABASE
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: MYSQL_DATABASE
        envFrom:
            - secretRef:
                name: app-secret
        ports:
          - containerPort: 3306
        volumeMounts:
          - name: data
            mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
