apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-deploy-v2
  name: nginx-deploy-v2
  namespace: shivang
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-deploy-v2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1          # max extra pods during update
      maxUnavailable: 0    # no downtime (0 = zero-downtime)
  template:
    metadata:
      labels:
        app: nginx-deploy-v2
    spec:
      containers:
      - image: mynginx:v2
        name: my-nginx
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
          - name: IMAGE_TAG
            value: "v2"
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        resources:
          requests:
            cpu: "5m"
            memory: "128Mi"
          limits:
            cpu: "10m"
            memory: "256Mi"
status: {}
