apiVersion: v1
kind: Service
metadata:
  labels:
    app: web-app-loadbalancer
  name: web-app-loadbalancer
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: web-app
  type: LoadBalancer
status:
  loadBalancer: {}
