apiVersion: v1
kind: ConfigMap
metadata:
  name: bankapp-config
  namespace: bankapp
data:
  OLLAMA_HOST: ollama-service # name of ollama svc
  OLLAMA_PORT: "11434"
  OLLAMA_URL: http://ollama-service:11434
  MYSQL_DATABASE: bankappdb
  MYSQL_PORT: "3306"  
  MYSQL_HOST: mysql-service # name of mysql svc
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"


  